#!/bin/sh

set -e

echo "==> Installing npm dependencies…"
npm install

echo "==> Installing bower dependencies…"
bower install

echo "==> Updating submodules…"
git submodule init && git submodule update
